---
# tasks file for ansible_role_mariadb_database_dump

- name: Databases dump
  shell: mysqldump -E -R -u "{{ ansible_role_mariadb_database_dump_mysql_user }}" -p"{{ ansible_role_mariadb_database_dump_mysql_password }}" -h "{{ ansible_role_mariadb_database_dump_mysql_host }}" --single-transaction --databases "{{ ansible_role_mariadb_database_dump_db }}" > {{ ansible_role_mariadb_database_dump_backup_path }}
